version: "3.7"
services:
  app: 
    build: ./app
    restart: always
    ports: 
      - "8080:8080"
  server:
    build: ./server
    restart: always
    environment: 
      - DB_HOST=localhost
      - DB=url-shortner
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: url-shortner
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:

networks:
  app-network:
    name: app-networkx  